services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate || exit 1; daphne -b 0.0.0.0 -p 8000 ProwlerAnalysis.asgi:application"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    user: "postgres"

  redis:
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    user: "redis"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A ProwlerAnalysis worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - static_volume:/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    user: "root"

volumes:
  postgres_data:
  static_volume:
