# Generated by Django 5.1.2 on 2025-03-27 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('related_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('status_code', models.CharField(max_length=50)),
                ('status_detail', models.TextField()),
                ('remediation_desc', models.TextField()),
                ('remediation_references', models.JSONField(default=list)),
                ('risk_details', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('resources', models.JSONField(blank=True, default=list)),
                ('parent_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.check')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.scan'),
        ),
        migrations.AlterUniqueTogether(
            name='check',
            unique_together={('scan', 'uid')},
        ),
    ]
